### ISSUE TITLE
Updating lwc-services from 3.0.4 to 3.1.0 is breaking Jest Tests

### ISSUE THREAD

**Issue by adityanaag3** [muenzpraeger/create-lwc-app#884]
### Summary

The `test:unit` script from package.json fails with the message `Cannot find module '@lwc/engine' from 'node_modules/@lwc/jest-preset/src/setup.js'` after updating the version of lwc-services to 3.1.0.

### Steps To Reproduce:

1.  Update the version of lwc-services in package.json to "lwc-services": "^3.1.0",
1.  Run `yarn install`
1.  Run `yarn test:unit`

### Expected result

Tests should run successfully

### Actual result

All the tests fail with the error
```
Test suite failed to run

    Cannot find module '@lwc/engine' from 'node_modules/@lwc/jest-preset/src/setup.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@lwc/jest-preset/src/setup.js:149:13)
```

**Comment by muenzpraeger** [comment]
I recommend to check this with the LWC team. With version `3.1.1` of `lwc-services` I see this error:

```
  ● Test suite failed to run

    ReferenceError: Node is not defined

      at Object.<anonymous> (node_modules/@lwc/synthetic-shadow/dist/synthetic-shadow.js:193:5)
      at Object.<anonymous> (node_modules/@lwc/jest-preset/src/setup.js:1:83)
```

As that comes from the core LWC Jest package it's out-of-scope for here. It is noteworthy that this does not apply to new projects that are created with `create-lwc-app`, so I'm unclear why this is happening.

FYI @pmdartus

**Comment by pmdartus** [comment]
Looking at the recent changes here, `@lwc/jest-preset` is currently not compatible with `jest@27` ([package.json](https://github.com/muenzpraeger/create-lwc-app/blob/main/packages/lwc-services/package.json#L38)). It will be added in the next minor version: https://github.com/salesforce/lwc-test/pull/123

Also something to keep in mind is that with `jest@27`, the default test environment is now node instead of jsdom ([post](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults)). If you haven't touched the `jest.config.json` this would explain why you see this error with `Node` not being defined.

I would recommend switching back to jest@26 until the `@lwc/jest-preset` is updated.

**Comment by muenzpraeger** [comment]
Fixed with #889
